### ISSUE TITLE
Question: What is the path of generated Apk?

### ISSUE THREAD

**Issue by Apsaliya** [mingchen/docker-android-build-box#16]
Sorry for asking usage question here!

after running 
```
image: mingc/android-build-box:latest

pipelines:
  default:
    - step:
        script:
          - chmod +x gradlew
          - ./gradlew assemble
```
It runs successfully. Now I want to upload generated Apk somewhere. Where do I access it?
