### ISSUE TITLE
Fastlane Error on Bitbucket Pipelines

### ISSUE THREAD

**Issue by jcchikikomori** [mingchen/docker-android-build-box#51]
Unable to load plugins, although I am done executing `bundle install`

![Screen Shot 2020-08-07 at 12 56 46 PM](https://user-images.githubusercontent.com/4709030/89610640-a0fb7f80-d8ad-11ea-94f8-ce34dc3daba1.png)

**Comment by jcchikikomori** [comment]
Pipeline snippet:
```yml
pipelines:
  pull-requests:
    feature/bitbucket-pipelines:
      - step:
          name: "Fastlane (Staging)"
          caches:
            - bundler
            - gradle
            - gradle-wrapper
          script:
            - echo "$KEYSTORE_PROPERTIES" | base64 -d > keystore.properties
            - echo "$KEY_BASE64" | base64 -d > app/keystore
            - echo "$GOOGLE_SERVICES_API" | base64 -d > app/google-api.json
            - echo "$GOOGLE_SERVICES_KEY" | base64 -d > app/google-services.json
            - echo "$FASTLANE_ENV" | base64 -d > fastlane/.env
            - bundle install
            - bundle exec fastlane init
            - bundle exec fastlane env
            - bundle exec fastlane install_plugins
            - bundle exec fastlane staging_release_ci
          artifacts:
            - app/build/outputs/apk/staging/debug/*.apk
```
