### ISSUE TITLE
GemFile

### ISSUE THREAD

**Issue by srockytfl** [mingchen/docker-android-build-box#54]
Hi, I'm trying to build a fastlane project with bitbucket pipeline, but my lane fails to find the plugins:

' Could not find action, lane or variable 'get_version_name'.'

My GemFile in my project root is like this:
`source "https://rubygems.org"
gem "fastlane"
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)`

But the fastlane isn't find it.  How can I solve this problem? thank you.

**Comment by FrancisLeigh** [comment]
I am also Having a similar issue
```
[05:47:38]: It seems like you wanted to load some plugins, however they couldn't be loaded
[05:47:38]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/



+---------------+-------+
|     Lane Context      |
+---------------+-------+
| PLATFORM_NAME |       |
| LANE_NAME     | build |
+---------------+-------+
[05:47:38]: Could not find action, lane or variable 'increment_version_code'. Check out the documentation for more details: https://docs.fastlane.tools/actions


[05:47:38]: fastlane finished with errors
[!] Could not find action, lane or variable 'increment_version_code'. Check out the documentation for more details: https://docs.fastlane.tools/actions
```

**Comment by mingchen** [comment]
Have you done `bundle install` before build?

Checkout [sample project ](https://github.com/mingchen/docker-android-build-box/tree/master/test_projects/SampleProject) for basic fastlane setup.

Build sample project with flastlane:

```
docker run \
   --rm \
   -v `pwd`:/project mingc/android-build-box \
   bash -c 'cd /project; fastlane build'
```

You can play fastlane setup with this sample project to troubleshooting your issue.

**Comment by FrancisLeigh** [comment]
This is my `.yaml` config

```yaml
.android:
    image: mingc/android-build-box:latest
    artifacts:
        paths:
            - fastlane/logs
    before_script:
        - export GRADLE_USER_HOME=$(pwd)/.gradle
        - bundle install
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches
build:android:
    extends: .android
    stage: build
    interruptible: true
    artifacts:
        paths:
            - android/app/build/outputs/apk/release
    script:
        - fastlane build platform:android
    only:
        - master
        - develop
        - merge_requests
```

**Comment by mingchen** [comment]
Since you install your plugins with bundle install, try to replace your fast lane command with bundle exec:

    bundle exec fastlane build ...

**Comment by FrancisLeigh** [comment]
@mingchen  Getting the same Errors. 

```yaml
.android:
    image: mingc/android-build-box:latest
    artifacts:
        paths:
            - fastlane/logs
    before_script:
        - export GRADLE_USER_HOME=$(pwd)/.gradle
        - bundle install
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches
build:android:
    extends: .android
    stage: build
    interruptible: true
    artifacts:
        paths:
            - android/app/build/outputs/apk/release
    script:
        - bundle exec fastlane build platform:android
    only:
        - master
        - develop
        - merge_requests
```

```bash
$ export GRADLE_USER_HOME=$(pwd)/.gradle
$ bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Using rake 13.0.1
Using CFPropertyList 3.0.2
Using public_suffix 4.0.6
Using addressable 2.7.0
Using atomos 0.1.3
Using aws-eventstream 1.1.0
Using aws-partitions 1.378.0
Using aws-sigv4 1.2.2
Using jmespath 1.4.0
Using aws-sdk-core 3.109.0
Using aws-sdk-kms 1.39.0
Using aws-sdk-s3 1.82.0
Using babosa 1.0.3
Using bundler 2.1.4
Using claide 1.0.3
Using colored 1.2
Using colored2 3.1.2
Using highline 1.7.10
Using commander-fastlane 4.4.6
Using declarative 0.0.20
Using declarative-option 0.1.0
Using digest-crc 0.6.1
Using unf_ext 0.0.7.7
Using unf 0.1.4
Using domain_name 0.5.20190701
Using dotenv 2.7.6
Using emoji_regex 3.0.0
Using excon 0.76.0
Using multipart-post 2.0.0
Using faraday 1.0.1
Using http-cookie 1.0.3
Using faraday-cookie_jar 0.0.7
Using faraday_middleware 1.0.0
Using fastimage 2.2.0
Using gh_inspector 1.1.3
Using jwt 2.2.2
Using memoist 0.16.2
Using multi_json 1.15.0
Using os 1.1.1
Using signet 0.14.0
Using googleauth 0.13.1
Using httpclient 2.8.3
Using mini_mime 1.0.2
Using uber 0.1.0
Using representable 3.0.4
Using retriable 3.1.2
Using google-api-client 0.38.0
Using google-cloud-env 1.3.3
Using google-cloud-errors 1.0.1
Using google-cloud-core 1.5.0
Using google-cloud-storage 1.29.0
Using json 2.3.1
Using mini_magick 4.10.1
Using plist 3.5.0
Using rubyzip 2.3.0
Using security 0.1.3
Using naturally 2.2.0
Using simctl 1.6.8
Using slack-notifier 2.3.2
Using terminal-notifier 2.0.0
Using unicode-display_width 1.7.0
Using terminal-table 1.8.0
Using tty-screen 0.8.1
Using tty-cursor 0.7.1
Using tty-spinner 0.9.3
Using word_wrap 1.0.0
Using nanaimo 0.3.0
Using xcodeproj 1.18.0
Using rouge 2.0.7
Using xcpretty 0.3.0
Using xcpretty-travis-formatter 1.0.0
Using fastlane 2.162.0
Bundle complete! 2 Gemfile dependencies, 72 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
$ bundle exec fastlane build platform:android
[03:23:42]: It seems like you wanted to load some plugins, however they couldn't be loaded
[03:23:42]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
[03:23:42]: Sending anonymous analytics information
[03:23:42]: Learn more at https://docs.fastlane.tools/#metrics
[03:23:42]: No personal or sensitive data is sent.
[03:23:42]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[03:23:42]: Driving the lane 'build' 🚀
[03:23:42]: --------------------------------------------------
[03:23:42]: --- Step: Switch to android_prepare_build lane ---
[03:23:42]: --------------------------------------------------
[03:23:42]: Cruising over to lane 'android_prepare_build' 🚖
[03:23:42]: -----------------------------------------------------------
[03:23:42]: --- Step: Switch to android_increment_build_number lane ---
[03:23:42]: -----------------------------------------------------------
[03:23:42]: Cruising over to lane 'android_increment_build_number' 🚖
+---------------+-------+
|     Lane Context      |
+---------------+-------+
| PLATFORM_NAME |       |
| LANE_NAME     | build |
+---------------+-------+
[03:23:42]: Could not find action, lane or variable 'increment_version_code'. Check out the documentation for more details: https://docs.fastlane.tools/actions
+------+-----------------------------------------------+-------------+
|                          fastlane summary                          |
+------+-----------------------------------------------+-------------+
| Step | Action                                        | Time (in s) |
+------+-----------------------------------------------+-------------+
| 1    | Switch to android_prepare_build lane          | 0           |
| 2    | Switch to android_increment_build_number lane | 0           |
+------+-----------------------------------------------+-------------+
[03:23:42]: fastlane finished with errors
[!] Could not find action, lane or variable 'increment_version_code'. Check out the documentation for more details: https://docs.fastlane.tools/actions
Cleaning up file based variables
00:00
ERROR: Job failed: exit code 1
```
