### ISSUE TITLE
Support for Android Gradle Plugin 7.0 needs Java 11

### ISSUE THREAD

**Issue by NinoDLC** [mingchen/docker-android-build-box#65]
Android Gradle Plugin 7.0+ [needs Java 11 to work](https://developer.android.com/studio/releases/gradle-plugin#jdk-11), but only Java 8 is bundled with Ubuntu 18.04.

Is an update on this image considered in order to run projects using AGP 7.0+ ?

**Comment by ozmium** [comment]
One possible workaround could be to manually install Java 11 into the Docker machine, and use the [Jenv](https://github.com/jenv/jenv) environment switcher:

```shell
# Install Jenv(https://www.jenv.be/)
git clone https://github.com/jenv/jenv.git ~/.jenv
echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(jenv init -)"' >> ~/.bash_profile
source ~/.bash_profile

# Add Java 11
jenv add /usr/lib/jvm/java-11-openjdk-amd64
jenv local system
```

Source: https://github.com/mingchen/docker-android-build-box/issues/58#issuecomment-894868703  from Github user **felHR85**

**Comment by mingchen** [comment]
Both java 8 and Java 11 are installed. Added `jenv` to make it easier to choose which one to use. 
see [Choose Java Version in README](https://github.com/mingchen/docker-android-build-box#choose-java-version)

**Comment by mateusz-bak** [comment]
My step in .drone.yml looks like this:

```
steps:
- name: build
  image: mingc/android-build-box:1.22.0
  commands:
  - . $HOME/.bash_profile
  - jenv local 11
  - ./gradlew build
```

And log from ci job is:
```
/bin/sh: 35: .: Can't open /root/.bash_profile
+ . $HOME/.bash_profile
```


Do you have any ideas what I'm doing wrong?

**Comment by Jargle** [comment]
@mingchen I am unable to use your container because of the previous errors in this thread. Gradle still is trying to use Java 8.

```
image: mingc/android-build-box:1.22.0

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
...

build:assembleApp:
  stage: build
  script:
    - ./gradlew assemble
```

Results in:

```
$ ./gradlew assemble
Downloading https://services.gradle.org/distributions/gradle-7.2-bin.zip
..........
10%...........20%...........30%...........40%...........50%......
.....60%...........70%...........80%...........90%...........100%
Welcome to Gradle 7.2!
Here are the highlights of this release:
 - Toolchain support for Scala
 - More cache hits when Java source files have platform-specific line endings
 - More resilient remote HTTP build cache behavior
For more details see https://docs.gradle.org/7.2/release-notes.html
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 
Configuration on demand is an incubating feature.
FAILURE: Build failed with an exception.
* Where:
Build file '/path/to/app_gradle/cut/build.gradle' line: 1
* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
```
